/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#2563EB",
        "primary-dark": "#1D4ED8",
        "primary-light": "#EFF6FF",
        secondary: "#7C3AED",
        success: "#22C55E",
        "success-light": "#F0FDF4",
        warning: "#F59E0B",
        "warning-light": "#FFFBEB",
        danger: "#EF4444",
        "danger-light": "#FEF2F2",
        background: "#F5F7FA",
        surface: "#FFFFFF",
        "surface-alt": "#F9FAFB",
        border: "#EDF0F5",
        text: "#111827",
        "text-secondary": "#6B7280",
        placeholder: "#9CA3AF",
        disabled: "#D1D5DB",
      },
      borderRadius: {
        sm: "6px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        full: "999px",
      },
      fontSize: {
        h1: "32px",
        h2: "28px",
        h3: "24px",
        title: "20px",
        body: "16px",
        caption: "14px",
        small: "12px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "40px",
        "3xl": "48px",
      },
    },
  },
  plugins: [],
};